version: '3.8'

services:
  frontend:
    build:
      context: ./frontendapp
    ports:
      - "3000:80"
    environment:
      - VITE_APP_RAZORPAY_KEY=rzp_test_674mfXBBMLrDhq
      - VITE_APP_BACKEND_URL=backend
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backendapp
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI_ATLAS=mongodb+srv://2200030963:2200030963@cluster0.ecgcucy.mongodb.net/ecomdb?retryWrites=true&w=majority&appName=Cluster0
      - RAZORPAY_KEY_ID=rzp_test_674mfXBBMLrDhq
      - RAZORPAY_KEY_SECRET=BjvqhpI4cEhYatBnPrQ4gkbV
      - JWT_SECRET_KEY=455790ae4f2e3ce5b081f5227d64373d8b272161b52c918038679c1bb61dc658
    restart: unless-stopped